In [17]:
import pandas as pd, numpy as np 
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import GradientBoostingClassifier
df = pd.read_csv('loan_default_day2.csv')

In [18]:
print("\nColumns:")
print(df.columns.tolist())

Columns:
['loan_id', 'applicant_name', 'age', 'employment_type', 'employment_years', 'monthly_income', 'loan_amount', 'loan_date', 'credit_score', 'region', 'collection_calls', 'recovery_amount', 'account_closed_date', 'risk_flag', 'late_but_repaid', 'defaulted_12m']

In [19]:
#Part A
print("Shape:", df.shape)
print(df.dtypes)
display(df.describe(include="number").T)
for col in df.select_dtypes(include="object").columns:
    print("\n" + "="*60)
    print(col)
    display(df[col].value_counts(dropna=False).head(20))

Shape: (5350, 16)
loan_id                  int64
applicant_name          object
age                      int64
employment_type         object
employment_years         int64
monthly_income         float64
loan_amount            float64
loan_date               object
credit_score             int64
region                  object
collection_calls         int64
recovery_amount        float64
account_closed_date     object
risk_flag               object
late_but_repaid         object
defaulted_12m            int64
dtype: object

,count,mean,std,min,25%,50%,75%,max
loan_id,5350.0,12569.532150,1487.996407,10001.0,11280.25,12569.5,13860.75,15150.0
age,5350.0,37.944112,9.801472,0.0,31.00,38.0,45.00,65.0
employment_years,5350.0,76.188785,240.216829,0.0,7.00,14.0,22.00,999.0
monthly_income,4595.0,39861.768894,148294.424572,0.0,24000.00,35200.0,48700.00,9999999.0
loan_amount,5350.0,434179.252336,286991.323949,24000.0,225000.00,366500.0,582750.00,2481000.0
credit_score,5350.0,681.059626,70.481009,436.0,633.00,681.0,727.00,900.0
collection_calls,5350.0,1.291963,2.711323,0.0,0.00,0.0,1.00,17.0
recovery_amount,5350.0,24892.635514,75527.705883,0.0,0.00,0.0,0.00,970100.0
defaulted_12m,5350.0,0.219252,0.413779,0.0,0.00,0.0,0.00,1.0

============================================================
applicant_name

applicant_name
Vijay Gohil        27
Pooja Bhatt        27
Sanjay Bhatt       27
Rekha Gohil        27
Nirav Rathod       27
Jignesh Zala       26
Dhruv Mehta        26
Harsh Shah         25
Bhavesh Solanki    25
Vijay Chauhan      24
Meera Jadeja       24
Amit Vora          24
Kiran Rathod       24
Meera Gohil        24
Amit Jadeja        24
Sanjay Zala        24
Jignesh Parmar     24
Mahesh Zala        24
Pooja Gohil        23
Kiran Jadeja       23
Name: count, dtype: int64

============================================================
employment_type

employment_type
Salaried         2117
Business         1073
Daily wage        838
Self-employed     836
Self employed     140
Self-Employed     124
SE                117
self employed     105
Name: count, dtype: int64

============================================================
loan_date

loan_date
2021-09-24    14
2022-07-21    14
2022-07-23    14
2021-11-03    13
2021-09-28    13
2021-05-05    13
2022-08-31    13
2022-05-17    12
2022-02-04    12
2022-08-28    12
2022-02-26    12
2022-09-30    12
2021-04-03    12
2022-06-21    12
2021-03-04    12
2021-07-27    12
2022-01-16    12
2023-02-10    12
2022-08-29    12
2022-04-25    12
Name: count, dtype: int64

============================================================
region

region
Saurashtra         1637
North Gujarat      1069
Central Gujarat    1037
Kutch               820
South Gujarat       787
Name: count, dtype: int64

============================================================
account_closed_date

account_closed_date
NaN           4413
2023-09-12       6
2023-06-13       6
2022-03-29       6
2022-10-10       6
2022-03-08       5
2023-11-03       5
2023-12-13       4
2023-04-16       4
2022-04-04       4
2023-03-24       4
2022-04-02       4
2022-12-24       4
2023-03-29       4
2023-05-09       4
2024-02-13       4
2023-08-18       4
2022-10-03       4
2023-03-10       4
2022-02-03       4
Name: count, dtype: int64

============================================================
risk_flag

risk_flag
low     4181
high    1169
Name: count, dtype: int64

============================================================
late_but_repaid

late_but_repaid
N    5016
Y     334
Name: count, dtype: int64

In [20]:
numeric_cols = df.select_dtypes(include=np.number).columns

for col in numeric_cols:
    print(f"\n--- {col} ---")
    print("min:", df[col].min())
    print("max:", df[col].max())
    print("unique values:", df[col].nunique())

--- loan_id ---
min: 10001
max: 15150
unique values: 5150

--- age ---
min: 0
max: 65
unique values: 46

--- employment_years ---
min: 0
max: 999
unique values: 45

--- monthly_income ---
min: 0.0
max: 9999999.0
unique values: 890

--- loan_amount ---
min: 24000.0
max: 2481000.0
unique values: 1112

--- credit_score ---
min: 436
max: 900
unique values: 386

--- collection_calls ---
min: 0
max: 17
unique values: 18

--- recovery_amount ---
min: 0.0
max: 970100.0
unique values: 718

--- defaulted_12m ---
min: 0
max: 1
unique values: 2

In [21]:
# part B

missing_table = pd.DataFrame({
    "missing_count": df.isna().sum(),
    "missing_percentage": df.isna().mean() * 100
}).sort_values("missing_percentage", ascending=False)

display(missing_table)

                     missing_count  missing_percentage
account_closed_date           4413           82.485981
monthly_income                 755           14.112150
age                              0            0.000000
loan_id                          0            0.000000
employment_type                  0            0.000000
employment_years                 0            0.000000
loan_amount                      0            0.000000
applicant_name                   0            0.000000
loan_date                        0            0.000000
credit_score                     0            0.000000
collection_calls                 0            0.000000
region                           0            0.000000
recovery_amount                  0            0.000000
risk_flag                        0            0.000000
late_but_repaid                  0            0.000000
defaulted_12m                    0            0.000000

In [22]:
# B2. Search for possible placeholder values in text columns

placeholder_candidates = [
    "", " ", "NA", "N/A", "na", "n/a",
    "NULL", "null", "None", "none",
    "-", "--", "unknown", "Unknown"
]

for col in df.select_dtypes(include="object").columns:
    print("\n" + "="*60)
    print("COLUMN:", col)

    counts = df[col].astype("string").value_counts(dropna=False)

    found = counts[
        counts.index.astype("string").str.strip().isin(placeholder_candidates)
    ]

    if len(found) == 0:
        print("No obvious placeholder values found.")
    else:
        display(found)

============================================================
COLUMN: applicant_name
No obvious placeholder values found.

============================================================
COLUMN: employment_type
No obvious placeholder values found.

============================================================
COLUMN: loan_date
No obvious placeholder values found.

============================================================
COLUMN: region
No obvious placeholder values found.

============================================================
COLUMN: account_closed_date
No obvious placeholder values found.

============================================================
COLUMN: risk_flag
No obvious placeholder values found.

============================================================
COLUMN: late_but_repaid
No obvious placeholder values found.

In [23]:
income_missing_comparison = (
    df.groupby(df["monthly_income"].isna())["defaulted_12m"]
      .agg(["count", "mean"])
      .rename(index={False: "Income present", True: "Income missing"})
)

income_missing_comparison["default_rate_percent"] = (
    income_missing_comparison["mean"] * 100
)

display(income_missing_comparison)

                count      mean  default_rate_percent
monthly_income
Income present   4595  0.163221             16.322089
Income missing    755  0.560265             56.026490

In [24]:
df["income_is_missing"] = df["monthly_income"].isna()

for col in ["age", "employment_type", "region", "credit_score", "defaulted_12m"]:
    if col in df.columns:
        print("\n", col)
        if df[col].dtype == "object":
            display(pd.crosstab(df[col], df["income_is_missing"], normalize="columns") * 100)
        else:
            display(df.groupby("income_is_missing")[col].agg(["count", "mean", "median"]))

 age

                   count       mean  median
income_is_missing
False               4595  37.873341    38.0
True                 755  38.374834    38.0

 employment_type

income_is_missing      False      True
employment_type
Business           20.435256  17.748344
Daily wage         15.408052  17.218543
SE                  2.241567   1.854305
Salaried           39.825898  38.013245
Self employed       2.568009   2.913907
Self-Employed       2.524483   1.059603
Self-employed      15.059848  19.072848
self employed       1.936888   2.119205

 region

income_is_missing      False      True
region
Central Gujarat    19.455930  18.940397
Kutch              15.016322  17.218543
North Gujarat      20.435256  17.218543
Saurashtra         30.293798  32.450331
South Gujarat      14.798694  14.172185

 credit_score

                   count        mean  median
income_is_missing
False               4595  683.575626   683.0
True                 755  665.747020   664.0

 defaulted_12m

                   count      mean  median
income_is_missing
False               4595  0.163221     0.0
True                 755  0.560265     1.0

In [26]:
df["account_closed_date"].value_counts(dropna=False).head(10)

account_closed_date
NaN           4413
2023-09-12       6
2023-06-13       6
2022-03-29       6
2022-10-10       6
2022-03-08       5
2023-11-03       5
2023-12-13       4
2023-04-16       4
2022-04-04       4
Name: count, dtype: int64

In [27]:
print("Missing account_closed_date by target:")
display(
    df.groupby(df["account_closed_date"].isna())["defaulted_12m"]
      .agg(["count", "mean"])
      .rename(index={
          False: "Date present",
          True: "Date missing"
      })
)

Missing account_closed_date by target:

                     count      mean
account_closed_date
Date present           937  0.819637
Date missing          4413  0.091774

In [35]:
from sklearn.model_selection import StratifiedKFold, cross_val_score
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression

# Target
y = df["defaulted_12m"]

# Remove target
X = df.drop(columns=["defaulted_12m"])

# Drop loan_id because it is an identifier, not a meaningful predictor
X = X.drop(columns=["loan_id"])

# Drop applicant_name because it is an identifier/name rather than a useful
# numeric or categorical modelling feature for this baseline
X = X.drop(columns=["applicant_name"])

# Convert loan_date and account_closed_date into useful numeric date features
for col in ["loan_date", "account_closed_date"]:
    X[col] = pd.to_datetime(X[col], errors="coerce")

    X[col + "_year"] = X[col].dt.year
    X[col + "_month"] = X[col].dt.month
    X[col + "_day"] = X[col].dt.day

    X = X.drop(columns=[col])

# Identify columns
numeric_features = X.select_dtypes(include=["number"]).columns
categorical_features = X.select_dtypes(include=["object", "category"]).columns

# Numeric preprocessing
numeric_transformer = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

# Categorical preprocessing
categorical_transformer = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("onehot", OneHotEncoder(handle_unknown="ignore"))
])

# Combine preprocessing
preprocessor = ColumnTransformer([
    ("num", numeric_transformer, numeric_features),
    ("cat", categorical_transformer, categorical_features)
])

# Baseline model
baseline_model = Pipeline([
    ("preprocessor", preprocessor),
    ("model", LogisticRegression(max_iter=1000))
])

# 5-fold stratified CV
cv = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

auc_scores = cross_val_score(
    baseline_model,
    X,
    y,
    cv=cv,
    scoring="roc_auc"
)

print("5-fold AUC scores:", auc_scores)
print("Mean 5-fold AUC:", auc_scores.mean())
print("Standard deviation:", auc_scores.std())

5-fold AUC scores: [0.88986014 0.91483151 0.88904064 0.89856542 0.91597911]
Mean 5-fold AUC: 0.9016553646922449
Standard deviation: 0.011718248589740804

In [36]:
suspicious_features = [
    "collection_calls",
    "recovery_amount",
    "account_closed_date",
    "risk_flag",
    "late_but_repaid"
]

results = []

for feature in suspicious_features:

    # Start with the same X used for the baseline
    X_test = X.copy()

    # account_closed_date was converted into 3 columns
    if feature == "account_closed_date":
        cols_to_remove = [
            "account_closed_date_year",
            "account_closed_date_month",
            "account_closed_date_day"
        ]
    else:
        cols_to_remove = [feature]

    # Check that the columns exist
    missing_cols = [
        col for col in cols_to_remove
        if col not in X_test.columns
    ]

    if missing_cols:
        print(f"Skipping {feature}: columns not found -> {missing_cols}")
        continue

    X_test = X_test.drop(columns=cols_to_remove)

    # Identify column types again
    numeric_features_test = X_test.select_dtypes(
        include=["number"]
    ).columns

    categorical_features_test = X_test.select_dtypes(
        include=["object", "category"]
    ).columns

    preprocessor_test = ColumnTransformer([
        ("num",
         Pipeline([
             ("imputer", SimpleImputer(strategy="median")),
             ("scaler", StandardScaler())
         ]),
         numeric_features_test),

        ("cat",
         Pipeline([
             ("imputer", SimpleImputer(strategy="most_frequent")),
             ("onehot", OneHotEncoder(handle_unknown="ignore"))
         ]),
         categorical_features_test)
    ])

    model_test = Pipeline([
        ("preprocessor", preprocessor_test),
        ("model", LogisticRegression(max_iter=1000))
    ])

    scores = cross_val_score(
        model_test,
        X_test,
        y,
        cv=cv,
        scoring="roc_auc"
    )

    mean_auc = scores.mean()

    results.append({
        "Removed feature": feature,
        "Mean AUC": mean_auc,
        "Change from baseline": mean_auc - auc_scores.mean()
    })

results_df = pd.DataFrame(results)

display(results_df)

       Removed feature  Mean AUC  Change from baseline
0     collection_calls  0.897437             -0.004218
1      recovery_amount  0.901730              0.000075
2  account_closed_date  0.902537              0.000881
3            risk_flag  0.900427             -0.001229
4      late_but_repaid  0.872945             -0.028711

In [37]:
#prt D
# D1. Exact duplicate rows

exact_duplicate_count = df.duplicated().sum()

print("Exact duplicate rows:", exact_duplicate_count)

# Show examples
display(df[df.duplicated(keep=False)].sort_values(
    by=df.columns.tolist()
).head(20))

Exact duplicate rows: 200

,loan_id,applicant_name,age,employment_type,employment_years,monthly_income,loan_amount,loan_date,credit_score,region,collection_calls,recovery_amount,account_closed_date,risk_flag,late_but_repaid,defaulted_12m,income_is_missing
4309,10004,Sanjay Parmar,21,Salaried,0,30100.0,571000.0,2021-01-08,705,Saurashtra,0,0.0,NaN,low,N,0,False
5228,10004,Sanjay Parmar,21,Salaried,0,30100.0,571000.0,2021-01-08,705,Saurashtra,0,0.0,NaN,low,N,0,False
4956,10017,Anita Gohil,56,Business,34,66000.0,386000.0,2021-03-09,616,Central Gujarat,0,0.0,NaN,low,N,0,False
5119,10017,Anita Gohil,56,Business,34,66000.0,386000.0,2021-03-09,616,Central Gujarat,0,0.0,NaN,low,N,0,False
1930,10111,Kiran Mehta,23,Business,1,50200.0,948000.0,2022-01-30,757,Kutch,0,0.0,NaN,low,N,0,False
3398,10111,Kiran Mehta,23,Business,1,50200.0,948000.0,2022-01-30,757,Kutch,0,0.0,NaN,low,N,0,False
2069,10117,Dhruv Parmar,44,Daily wage,17,14000.0,175000.0,2022-02-20,701,Saurashtra,1,0.0,NaN,low,N,0,False
3599,10117,Dhruv Parmar,44,Daily wage,17,14000.0,175000.0,2022-02-20,701,Saurashtra,1,0.0,NaN,low,N,0,False
1095,10129,Kinjal Shah,47,Business,22,38300.0,465000.0,2022-02-25,651,Central Gujarat,0,0.0,NaN,low,N,0,False
4055,10129,Kinjal Shah,47,Business,22,38300.0,465000.0,2022-02-25,651,Central Gujarat,0,0.0,NaN,low,N,0,False
3987,10134,Vijay Zala,41,Daily wage,19,16800.0,271000.0,2021-06-30,697,South Gujarat,0,0.0,NaN,low,N,0,False
4267,10134,Vijay Zala,41,Daily wage,19,16800.0,271000.0,2021-06-30,697,South Gujarat,0,0.0,NaN,low,N,0,False
628,10150,Priya Vora,37,Salaried,12,NaN,713000.0,2021-10-22,793,Kutch,0,0.0,NaN,low,N,0,True
732,10150,Priya Vora,37,Salaried,12,NaN,713000.0,2021-10-22,793,Kutch,0,0.0,NaN,low,N,0,True
87,10171,Kiran Jadeja,21,Self-employed,0,36600.0,201000.0,2022-09-20,598,Saurashtra,0,0.0,NaN,low,N,0,False
691,10171,Kiran Jadeja,21,Self-employed,0,36600.0,201000.0,2022-09-20,598,Saurashtra,0,0.0,NaN,low,N,0,False
844,10176,Rekha Gohil,36,Self-employed,15,NaN,897000.0,2021-04-08,701,North Gujarat,1,0.0,NaN,low,N,0,True
2232,10176,Rekha Gohil,36,Self-employed,15,NaN,897000.0,2021-04-08,701,North Gujarat,1,0.0,NaN,low,N,0,True
1162,10202,Harsh Parmar,33,Salaried,9,46600.0,238000.0,2023-03-10,560,Central Gujarat,0,0.0,NaN,low,N,0,False
3082,10202,Harsh Parmar,33,Salaried,9,46600.0,238000.0,2023-03-10,560,Central Gujarat,0,0.0,NaN,low,N,0,False

In [40]:
import re

In [54]:
# VERIFY near-duplicates
# Ignore loan_id because near-duplicates receive a new ID.
# Name formatting and monthly income can change.

# Normalize name
df["name_norm"] = (
    df["applicant_name"]
    .astype(str)
    .str.lower()
    .str.replace(r"[^a-z0-9]", "", regex=True)
)

# Normalize employment type
df["employment_norm"] = (
    df["employment_type"]
    .astype(str)
    .str.lower()
    .str.replace("-", "", regex=False)
    .str.replace(" ", "", regex=False)
)

# Income can be rounded in near-duplicates
df["income_norm"] = df["monthly_income"].round(-3)

# Fields that should remain the same for a true near-duplicate
check_cols = [
    "name_norm",
    "age",
    "employment_norm",
    "employment_years",
    "income_norm",
    "loan_amount",
    "loan_date",
    "credit_score",
    "region"
]

# Find candidate groups
groups = (
    df.groupby(check_cols, dropna=False)
      .size()
      .reset_index(name="count")
)

groups = groups[groups["count"] > 1]

print("Candidate groups:", len(groups))

# Get actual rows
candidates = df.merge(
    groups[check_cols],
    on=check_cols,
    how="inner"
)

# Remove exact duplicate rows first
candidates_no_exact = candidates.drop_duplicates(
    subset=[
        "applicant_name", "age", "employment_type",
        "employment_years", "monthly_income",
        "loan_amount", "loan_date", "credit_score",
        "region", "defaulted_12m"
    ]
)

print("Candidate rows after removing exact duplicates:",
      len(candidates_no_exact))

display(
    candidates_no_exact[
        [
            "loan_id",
            "applicant_name",
            "age",
            "employment_type",
            "employment_years",
            "monthly_income",
            "loan_amount",
            "loan_date",
            "credit_score",
            "region",
            "defaulted_12m"
        ]
    ].head(50)
)

Candidate groups: 343
Candidate rows after removing exact duplicates: 493

,loan_id,applicant_name,age,employment_type,employment_years,monthly_income,loan_amount,loan_date,credit_score,region,defaulted_12m
0,10867,Kiran Vora,46,self employed,18,NaN,340000.0,2022-10-09,707,Saurashtra,0
1,12616,Ravi Rathod,43,Salaried,20,51300.00,407000.0,2022-11-12,679,Central Gujarat,1
2,10208,Bhavesh Vora,31,Business,3,57000.00,993000.0,2021-10-19,742,Saurashtra,0
3,13881,Kiran Joshi,63,Business,36,35900.00,556000.0,2022-07-23,772,South Gujarat,0
4,13131,Rekha Vora,31,Salaried,6,32700.00,379000.0,2021-07-05,673,Kutch,0
5,14576,Mahesh Jadeja,43,Business,16,0.38,639000.0,2021-09-24,649,South Gujarat,0
6,11510,Kiran Trivedi,47,Business,999,41600.00,344000.0,2023-06-12,730,Central Gujarat,0
7,11354,Rekha Vora,49,Salaried,21,33100.00,287000.0,2023-03-01,615,South Gujarat,0
8,14822,Bhavesh Patel,35,Salaried,7,26400.00,104000.0,2021-02-10,676,South Gujarat,1
9,12997,Jignesh Vora,23,Business,999,46500.00,673000.0,2022-10-13,793,Central Gujarat,0
10,13102,Nisha Vora,43,Daily wage,21,18200.00,287000.0,2023-04-23,626,Central Gujarat,0
11,14357,Ravi Bhatt,21,Salaried,0,36600.00,323000.0,2022-09-28,774,Kutch,1
12,13226,Harsh Shah,41,Daily wage,15,12100.00,104000.0,2022-07-23,726,Central Gujarat,0
13,14762,Bhavesh Joshi,37,Salaried,13,48300.00,273000.0,2022-08-17,649,Central Gujarat,1
14,14281,Harsh Trivedi,33,Salaried,6,27800.00,509000.0,2021-11-13,779,Central Gujarat,0
15,13230,Vijay Chauhan,28,Business,6,48000.00,851000.0,2021-04-11,620,Saurashtra,0
16,10171,Kiran Jadeja,21,Self-employed,0,36600.00,201000.0,2022-09-20,598,Saurashtra,0
17,11750,Amit Shah,22,Salaried,999,NaN,386000.0,2021-10-28,684,North Gujarat,0
18,11661,Nisha Dave,30,Salaried,9,17900.00,147000.0,2022-08-23,782,South Gujarat,0
19,10386,Amit Gohil,25,Self-employed,4,24700.00,228000.0,2023-01-30,604,North Gujarat,0
20,14132,Pooja Patel,21,Salaried,0,31800.00,312000.0,2021-07-18,629,Saurashtra,0
21,11026,Bhavesh Patel,43,Business,15,58600.00,639000.0,2021-10-23,692,South Gujarat,0
22,11729,Ravi Rathod,46,Salaried,20,33300.00,504000.0,2021-08-01,745,Kutch,0
23,11985,Mahesh Jadeja,39,Salaried,999,39300.00,596000.0,2022-10-14,732,South Gujarat,0
24,11915,Meera Vora,36,Salaried,999,49800.00,827000.0,2021-01-07,761,North Gujarat,0
25,12956,Vijay Rathod,52,Salaried,29,63200.00,611000.0,2022-08-04,605,North Gujarat,0
26,14439,Anita Bhatt,34,Business,999,71900.00,529000.0,2023-05-13,719,Central Gujarat,0
27,10180,Ravi Dave,23,Business,0,61700.00,232000.0,2022-05-27,596,Saurashtra,0
28,13300,Vijay Patel,49,Daily wage,22,13200.00,108000.0,2022-04-21,709,Saurashtra,0
29,11111,Nisha Rathod,49,Self-employed,28,37900.00,339000.0,2021-01-06,748,Saurashtra,0
30,11632,Rekha Mehta,42,Self employed,15,37400.00,530000.0,2023-06-13,761,North Gujarat,0
31,12162,Nirav Vora,28,Business,6,31000.00,592000.0,2021-01-27,769,Kutch,0
32,15034,mahesh solanki,29,Salaried,6,47000.00,410000.0,2021-12-07,653,North Gujarat,0
33,10550,Priya Zala,59,Salaried,33,31300.00,428000.0,2022-02-06,618,Kutch,0
34,13538,Priya Vora,31,Salaried,9,42700.00,768000.0,2021-07-25,687,Saurashtra,0
35,14860,Priya Joshi,47,Business,26,NaN,729000.0,2023-03-27,694,Central Gujarat,1
36,14026,Ravi Zala,38,Self-employed,12,18200.00,291000.0,2022-07-31,716,Saurashtra,0
37,15005,kiran rathod,27,Self-employed,6,20000.00,80000.0,2021-09-14,716,Saurashtra,0
38,11518,Dipti Gohil,45,Self-employed,18,NaN,434000.0,2022-03-02,646,Saurashtra,1
39,10773,Harsh Trivedi,31,Salaried,8,28000.00,375000.0,2021-04-23,629,Central Gujarat,0
40,12825,Harsh Trivedi,48,Self-employed,27,48300.00,372000.0,2021-09-09,678,North Gujarat,0
41,15052,kiran mehta,44,Self employed,17,45000.00,643000.0,2022-05-18,480,Kutch,1
42,12112,Hetal Joshi,33,Salaried,9,37000.00,453000.0,2021-02-17,553,Saurashtra,0
43,14597,Kiran Jadeja,32,Salaried,8,NaN,453000.0,2022-04-23,603,Saurashtra,1
44,15116,mahesh jadeja,43,Business,16,0.00,639000.0,2021-09-24,649,South Gujarat,0
45,11606,Ravi Vora,48,Business,26,67800.00,993000.0,2021-05-27,717,Kutch,1
46,10413,Harsh Chauhan,39,Salaried,11,54700.00,780000.0,2022-04-10,692,Central Gujarat,0
47,12613,Amit Gohil,47,Salaried,26,32600.00,136000.0,2021-04-30,757,North Gujarat,0
48,12397,Sanjay Joshi,45,Daily wage,24,16800.00,144000.0,2021-06-25,726,Central Gujarat,0
49,14308,Nirav Rathod,27,Daily wage,6,16100.00,66000.0,2021-07-04,635,Saurashtra,0

In [53]:
# FINAL VERIFICATION OF NEAR-DUPLICATES

# Fields that should be the same for a true near-duplicate
# loan_id is intentionally excluded because the generated near-duplicate gets a new ID.

verify_cols = [
    "name_norm",
    "age",
    "employment_norm",
    "employment_years",
    "income_norm",
    "loan_amount",
    "loan_date",
    "credit_score",
    "region"
]

# Find groups with the same normalized information
groups = (
    df.groupby(verify_cols, dropna=False)
      .size()
      .reset_index(name="count")
)

groups = groups[groups["count"] > 1]

# Get all candidate records
candidates = df.merge(
    groups[verify_cols],
    on=verify_cols,
    how="inner"
)

# Remove exact duplicates first
candidates = candidates.drop_duplicates()

# A true near-duplicate must have different loan IDs.
# Count rows that belong to groups with >1 UNIQUE loan_id.
verified_groups = (
    candidates.groupby(verify_cols, dropna=False)["loan_id"]
    .nunique()
    .reset_index(name="unique_loan_ids")
)

verified_groups = verified_groups[
    verified_groups["unique_loan_ids"] > 1
]

# Get the actual verified near-duplicate rows
verified = candidates.merge(
    verified_groups[verify_cols],
    on=verify_cols,
    how="inner"
)

print("Candidate groups:", len(groups))
print("Verified near-duplicate groups:", len(verified_groups))
print("Verified near-duplicate rows:", len(verified))

# Show examples
display(
    verified[
        [
            "loan_id",
            "applicant_name",
            "age",
            "employment_type",
            "employment_years",
            "monthly_income",
            "loan_amount",
            "loan_date",
            "credit_score",
            "region",
            "defaulted_12m"
        ]
    ].head(50)
)

Candidate groups: 343
Verified near-duplicate groups: 150
Verified near-duplicate rows: 300

,loan_id,applicant_name,age,employment_type,employment_years,monthly_income,loan_amount,loan_date,credit_score,region,defaulted_12m
0,10867,Kiran Vora,46,self employed,18,NaN,340000.0,2022-10-09,707,Saurashtra,0
1,13881,Kiran Joshi,63,Business,36,35900.00,556000.0,2022-07-23,772,South Gujarat,0
2,13131,Rekha Vora,31,Salaried,6,32700.00,379000.0,2021-07-05,673,Kutch,0
3,14576,Mahesh Jadeja,43,Business,16,0.38,639000.0,2021-09-24,649,South Gujarat,0
4,11510,Kiran Trivedi,47,Business,999,41600.00,344000.0,2023-06-12,730,Central Gujarat,0
5,12997,Jignesh Vora,23,Business,999,46500.00,673000.0,2022-10-13,793,Central Gujarat,0
6,14762,Bhavesh Joshi,37,Salaried,13,48300.00,273000.0,2022-08-17,649,Central Gujarat,1
7,14281,Harsh Trivedi,33,Salaried,6,27800.00,509000.0,2021-11-13,779,Central Gujarat,0
8,13230,Vijay Chauhan,28,Business,6,48000.00,851000.0,2021-04-11,620,Saurashtra,0
9,11750,Amit Shah,22,Salaried,999,NaN,386000.0,2021-10-28,684,North Gujarat,0
10,10386,Amit Gohil,25,Self-employed,4,24700.00,228000.0,2023-01-30,604,North Gujarat,0
11,11026,Bhavesh Patel,43,Business,15,58600.00,639000.0,2021-10-23,692,South Gujarat,0
12,11729,Ravi Rathod,46,Salaried,20,33300.00,504000.0,2021-08-01,745,Kutch,0
13,11915,Meera Vora,36,Salaried,999,49800.00,827000.0,2021-01-07,761,North Gujarat,0
14,12956,Vijay Rathod,52,Salaried,29,63200.00,611000.0,2022-08-04,605,North Gujarat,0
15,14439,Anita Bhatt,34,Business,999,71900.00,529000.0,2023-05-13,719,Central Gujarat,0
16,10180,Ravi Dave,23,Business,0,61700.00,232000.0,2022-05-27,596,Saurashtra,0
17,13300,Vijay Patel,49,Daily wage,22,13200.00,108000.0,2022-04-21,709,Saurashtra,0
18,11111,Nisha Rathod,49,Self-employed,28,37900.00,339000.0,2021-01-06,748,Saurashtra,0
19,12162,Nirav Vora,28,Business,6,31000.00,592000.0,2021-01-27,769,Kutch,0
20,15034,mahesh solanki,29,Salaried,6,47000.00,410000.0,2021-12-07,653,North Gujarat,0
21,10550,Priya Zala,59,Salaried,33,31300.00,428000.0,2022-02-06,618,Kutch,0
22,14860,Priya Joshi,47,Business,26,NaN,729000.0,2023-03-27,694,Central Gujarat,1
23,14026,Ravi Zala,38,Self-employed,12,18200.00,291000.0,2022-07-31,716,Saurashtra,0
24,15005,kiran rathod,27,Self-employed,6,20000.00,80000.0,2021-09-14,716,Saurashtra,0
25,11518,Dipti Gohil,45,Self-employed,18,NaN,434000.0,2022-03-02,646,Saurashtra,1
26,10773,Harsh Trivedi,31,Salaried,8,28000.00,375000.0,2021-04-23,629,Central Gujarat,0
27,15052,kiran mehta,44,Self employed,17,45000.00,643000.0,2022-05-18,480,Kutch,1
28,12112,Hetal Joshi,33,Salaried,9,37000.00,453000.0,2021-02-17,553,Saurashtra,0
29,14597,Kiran Jadeja,32,Salaried,8,NaN,453000.0,2022-04-23,603,Saurashtra,1
30,15116,mahesh jadeja,43,Business,16,0.00,639000.0,2021-09-24,649,South Gujarat,0
31,11606,Ravi Vora,48,Business,26,67800.00,993000.0,2021-05-27,717,Kutch,1
32,12613,Amit Gohil,47,Salaried,26,32600.00,136000.0,2021-04-30,757,North Gujarat,0
33,12397,Sanjay Joshi,45,Daily wage,24,16800.00,144000.0,2021-06-25,726,Central Gujarat,0
34,14308,Nirav Rathod,27,Daily wage,6,16100.00,66000.0,2021-07-04,635,Saurashtra,0
35,11639,Kinjal Shah,45,Self-Employed,24,29200.00,141000.0,2023-05-10,756,South Gujarat,0
36,15101,hetal chauhan,29,Salaried,7,39000.00,252000.0,2022-02-10,781,North Gujarat,0
37,11585,Jignesh Gohil,31,Business,9,80500.00,1058000.0,2021-05-27,789,North Gujarat,0
38,15107,dhruv jadeja,46,Self-employed,19,NaN,430000.0,2023-05-30,761,Kutch,1
39,15021,ravi parmar,29,Daily wage,8,14000.00,159000.0,2021-05-25,683,Central Gujarat,1
40,12475,Bhavesh Mehta,27,Self-employed,0,22800.00,416000.0,2021-08-17,608,North Gujarat,0
41,12263,Ravi Shah,54,Daily wage,28,21000.00,281000.0,2023-04-26,770,Kutch,1
42,15123,dhruv parmar,34,Daily wage,7,12000.00,99000.0,2023-04-12,698,Saurashtra,0
43,13602,Anita Dave,43,Daily wage,19,7800.00,124000.0,2021-06-29,730,South Gujarat,0
44,12636,Vijay Dave,26,Salaried,0,NaN,291000.0,2022-09-12,730,North Gujarat,0
45,15060,meera zala,36,Business,12,42000.00,249000.0,2021-11-13,569,Kutch,0
46,13385,Nirav Joshi,41,Daily wage,14,18200.00,345000.0,2022-12-22,750,Central Gujarat,0
47,10549,Dhruv Parmar,46,Self-employed,23,23000.00,212000.0,2021-05-25,635,North Gujarat,1
48,15025,DIPTI SOLANKI,29,Self-employed,1,26000.00,189000.0,2022-11-14,653,North Gujarat,0
49,11520,Ravi Solanki,28,Self-employed,2,22700.00,170000.0,2023-01-05,724,North Gujarat,0

In [46]:
# Identify exact duplicate rows in the original dataframe
duplicate_mask = df.duplicated(keep="first")

print("Exact duplicate rows:", duplicate_mask.sum())

# Remove duplicate rows from df
df_no_duplicates = df.drop_duplicates().copy()

print("Original shape:", df.shape)
print("After removing duplicates:", df_no_duplicates.shape)

Exact duplicate rows: 200
Original shape: (5350, 17)
After removing duplicates: (5150, 17)

In [47]:
from sklearn.model_selection import StratifiedKFold, cross_val_score
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression

# --------------------------------------------------
# 1. Remove exact duplicate rows
# --------------------------------------------------

df_no_duplicates = df.drop_duplicates().copy()

print("Original dataset shape:", df.shape)
print("Dataset shape after removing duplicates:", df_no_duplicates.shape)
print("Exact duplicate rows removed:", len(df) - len(df_no_duplicates))


# --------------------------------------------------
# 2. Target
# --------------------------------------------------

y = df_no_duplicates["defaulted_12m"]


# --------------------------------------------------
# 3. Features
# --------------------------------------------------

X = df_no_duplicates.drop(columns=["defaulted_12m"])

# Remove identifiers
X = X.drop(columns=["loan_id"])
X = X.drop(columns=["applicant_name"])


# --------------------------------------------------
# 4. Convert date columns
# --------------------------------------------------

for col in ["loan_date", "account_closed_date"]:

    X[col] = pd.to_datetime(X[col], errors="coerce")

    X[col + "_year"] = X[col].dt.year
    X[col + "_month"] = X[col].dt.month
    X[col + "_day"] = X[col].dt.day

    X = X.drop(columns=[col])


# --------------------------------------------------
# 5. Identify numerical and categorical features
# --------------------------------------------------

numeric_features = X.select_dtypes(
    include=["number"]
).columns

categorical_features = X.select_dtypes(
    include=["object", "category"]
).columns


# --------------------------------------------------
# 6. Preprocessing
# --------------------------------------------------

numeric_transformer = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

categorical_transformer = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("onehot", OneHotEncoder(handle_unknown="ignore"))
])

preprocessor = ColumnTransformer([
    ("num", numeric_transformer, numeric_features),
    ("cat", categorical_transformer, categorical_features)
])


# --------------------------------------------------
# 7. Logistic Regression model
# --------------------------------------------------

model_no_duplicates = Pipeline([
    ("preprocessor", preprocessor),
    ("model", LogisticRegression(max_iter=1000))
])


# --------------------------------------------------
# 8. Same 5-fold CV as baseline
# --------------------------------------------------

cv = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)


# --------------------------------------------------
# 9. Calculate AUC
# --------------------------------------------------

auc_scores_no_duplicates = cross_val_score(
    model_no_duplicates,
    X,
    y,
    cv=cv,
    scoring="roc_auc"
)


# --------------------------------------------------
# 10. Results
# --------------------------------------------------

print("5-fold AUC scores after removing duplicates:",
      auc_scores_no_duplicates)

print("Mean 5-fold AUC after removing duplicates:",
      auc_scores_no_duplicates.mean())

print("Standard deviation:",
      auc_scores_no_duplicates.std())

Original dataset shape: (5350, 17)
Dataset shape after removing duplicates: (5150, 17)
Exact duplicate rows removed: 200
5-fold AUC scores after removing duplicates: [0.91643552 0.88520891 0.90476269 0.90174511 0.9020249 ]
Mean 5-fold AUC after removing duplicates: 0.9020354254259739
Standard deviation: 0.009980147502042933

In [48]:
# Find rows where defaulted_12m = 0 but other evidence looks suspicious

suspicious_labels = df[
    (df["defaulted_12m"] == 0) &
    (
        (df["collection_calls"] > 0) |
        (df["recovery_amount"] > 0) |
        (df["account_closed_date"].notna()) |
        (df["risk_flag"].astype(str).str.lower().isin(["high", "medium"]))
    )
].copy()

print("Number of suspicious label candidates:",
      len(suspicious_labels))

display(
    suspicious_labels[
        [
            "loan_id",
            "applicant_name",
            "collection_calls",
            "recovery_amount",
            "account_closed_date",
            "risk_flag",
            "late_but_repaid",
            "defaulted_12m"
        ]
    ].head(20)
)


suspicious_labels["evidence_count"] = (
    (suspicious_labels["collection_calls"] > 0).astype(int) +
    (suspicious_labels["recovery_amount"] > 0).astype(int) +
    (suspicious_labels["account_closed_date"].notna()).astype(int) +
    (
        suspicious_labels["risk_flag"]
        .astype(str)
        .str.lower()
        .isin(["high", "medium"])
    ).astype(int)
)

# Strongest candidates first
suspicious_labels = suspicious_labels.sort_values(
    "evidence_count",
    ascending=False
)

display(
    suspicious_labels[
        [
            "loan_id",
            "applicant_name",
            "collection_calls",
            "recovery_amount",
            "account_closed_date",
            "risk_flag",
            "late_but_repaid",
            "defaulted_12m",
            "evidence_count"
        ]
    ].head(20)
)

Number of suspicious label candidates: 1190

,loan_id,applicant_name,collection_calls,recovery_amount,account_closed_date,risk_flag,late_but_repaid,defaulted_12m
0,10136,Sanjay Patel,0,0.0,2023-04-27,low,N,0
1,10825,Kinjal Solanki,2,0.0,2023-01-09,low,N,0
6,11462,Vijay Mehta,1,0.0,NaN,low,N,0
8,13134,Anita Gohil,1,0.0,NaN,low,N,0
10,11736,Vijay Vora,1,0.0,NaN,low,N,0
11,13846,Vijay Rathod,1,0.0,NaN,low,N,0
12,10135,Priya Parmar,2,0.0,NaN,low,N,0
19,10771,Vijay Jadeja,1,0.0,NaN,low,N,0
20,11037,Nirav Chauhan,1,0.0,NaN,low,N,0
22,13791,Hetal Jadeja,1,0.0,NaN,low,N,0
23,11117,Priya Chauhan,1,0.0,NaN,high,N,0
34,13131,Rekha Vora,1,0.0,NaN,low,N,0
38,14576,Mahesh Jadeja,7,371500.0,2022-04-15,high,N,0
42,11354,Rekha Vora,0,0.0,NaN,high,N,0
45,12513,Pooja Dave,0,0.0,NaN,high,N,0
51,13834,Harsh Jadeja,1,0.0,NaN,low,N,0
54,14749,Kiran Jadeja,6,37300.0,2021-12-16,high,N,0
76,10295,Amit Dave,1,0.0,NaN,low,Y,0
77,13369,Anita Zala,0,0.0,NaN,high,N,0
81,13854,Mahesh Chauhan,1,0.0,NaN,low,N,0

,loan_id,applicant_name,collection_calls,recovery_amount,account_closed_date,risk_flag,late_but_repaid,defaulted_12m,evidence_count
722,14759,Dhruv Gohil,4,113900.0,2022-01-17,high,N,0,4
2274,14638,Priya Solanki,8,325200.0,2022-12-31,high,N,0,4
1604,14783,Kinjal Solanki,5,273000.0,2024-04-17,high,N,0,4
4985,14921,Kiran Rathod,7,254900.0,2021-09-29,high,N,0,4
925,13541,Priya Trivedi,8,383300.0,2023-04-28,high,N,0,4
697,14174,Vijay Rathod,8,303500.0,2023-03-10,high,N,0,4
1613,14492,Mahesh Mehta,11,185100.0,2023-01-10,high,N,0,4
537,14577,Vijay Zala,8,21600.0,2023-12-28,high,N,0,4
690,13353,Priya Dave,7,50000.0,2023-08-24,high,N,0,4
2344,14558,Pooja Solanki,4,437300.0,2024-02-29,high,N,0,4
5054,14601,Mahesh Vora,4,53000.0,2022-05-25,high,N,0,4
2021,13984,Pooja Gohil,7,205800.0,2022-12-27,high,N,0,4
2502,14500,Kinjal Dave,10,165900.0,2022-04-18,high,N,0,4
2212,13743,Dipti Chauhan,8,51100.0,2023-11-04,high,N,0,4
2148,13439,Kiran Shah,3,25900.0,2022-10-21,high,N,0,4
1567,14714,Pooja Parmar,9,195300.0,2023-11-15,high,N,0,4
120,14942,Kinjal Shah,7,93800.0,2023-02-02,high,N,0,4
1073,13697,Harsh Solanki,8,277900.0,2023-07-09,high,N,0,4
1371,14704,Mahesh Trivedi,5,324200.0,2022-04-17,high,N,0,4
275,15116,mahesh jadeja,7,371500.0,2022-04-15,high,N,0,4

In [49]:
inspection_20 = suspicious_labels.head(20).copy()

display(
    inspection_20[
        [
            "loan_id",
            "applicant_name",
            "age",
            "employment_type",
            "monthly_income",
            "loan_amount",
            "credit_score",
            "region",
            "collection_calls",
            "recovery_amount",
            "account_closed_date",
            "risk_flag",
            "late_but_repaid",
            "defaulted_12m",
            "evidence_count"
        ]
    ]
)

,loan_id,applicant_name,age,employment_type,monthly_income,loan_amount,credit_score,region,collection_calls,recovery_amount,account_closed_date,risk_flag,late_but_repaid,defaulted_12m,evidence_count
722,14759,Dhruv Gohil,43,Self employed,NaN,256000.0,569,South Gujarat,4,113900.0,2022-01-17,high,N,0,4
2274,14638,Priya Solanki,26,Salaried,60600.0,1056000.0,665,South Gujarat,8,325200.0,2022-12-31,high,N,0,4
1604,14783,Kinjal Solanki,50,Salaried,31600.0,489000.0,671,Saurashtra,5,273000.0,2024-04-17,high,N,0,4
4985,14921,Kiran Rathod,45,self employed,47900.0,447000.0,536,South Gujarat,7,254900.0,2021-09-29,high,N,0,4
925,13541,Priya Trivedi,47,Business,NaN,931000.0,619,Kutch,8,383300.0,2023-04-28,high,N,0,4
697,14174,Vijay Rathod,42,Business,60400.0,916000.0,635,South Gujarat,8,303500.0,2023-03-10,high,N,0,4
1613,14492,Mahesh Mehta,48,Self-Employed,32500.0,322000.0,753,Central Gujarat,11,185100.0,2023-01-10,high,N,0,4
537,14577,Vijay Zala,44,Self-employed,18900.0,103000.0,618,Central Gujarat,8,21600.0,2023-12-28,high,N,0,4
690,13353,Priya Dave,44,Self-employed,15200.0,87000.0,567,Central Gujarat,7,50000.0,2023-08-24,high,N,0,4
2344,14558,Pooja Solanki,41,Salaried,48200.0,792000.0,590,Saurashtra,4,437300.0,2024-02-29,high,N,0,4
5054,14601,Mahesh Vora,27,Business,68500.0,299000.0,711,North Gujarat,4,53000.0,2022-05-25,high,N,0,4
2021,13984,Pooja Gohil,29,Salaried,61600.0,699000.0,647,Saurashtra,7,205800.0,2022-12-27,high,N,0,4
2502,14500,Kinjal Dave,55,Self-employed,32800.0,454000.0,709,Saurashtra,10,165900.0,2022-04-18,high,N,0,4
2212,13743,Dipti Chauhan,30,Self employed,19100.0,95000.0,585,Central Gujarat,8,51100.0,2023-11-04,high,N,0,4
2148,13439,Kiran Shah,44,Daily wage,9900.0,163000.0,558,South Gujarat,3,25900.0,2022-10-21,high,N,0,4
1567,14714,Pooja Parmar,41,Salaried,36600.0,407000.0,600,South Gujarat,9,195300.0,2023-11-15,high,N,0,4
120,14942,Kinjal Shah,27,Salaried,18500.0,174000.0,670,Saurashtra,7,93800.0,2023-02-02,high,N,0,4
1073,13697,Harsh Solanki,25,Business,36400.0,490000.0,687,Kutch,8,277900.0,2023-07-09,high,N,0,4
1371,14704,Mahesh Trivedi,27,Self-employed,45400.0,690000.0,566,North Gujarat,5,324200.0,2022-04-17,high,N,0,4
275,15116,mahesh jadeja,43,Business,0.0,639000.0,649,South Gujarat,7,371500.0,2022-04-15,high,N,0,4

In [50]:
# Check consistency of "late_but_repaid" labelling across regions

print("=== Overall relationship ===")
overall = df.groupby("late_but_repaid")["defaulted_12m"].agg(
    count="count",
    default_rate="mean"
)
overall["default_rate_%"] = overall["default_rate"] * 100
display(overall)


print("\n=== By Region ===")
region_check = df.groupby(
    ["region", "late_but_repaid"]
)["defaulted_12m"].agg(
    count="count",
    default_rate="mean"
).reset_index()

region_check["default_rate_%"] = region_check["default_rate"] * 100
display(region_check)


print("\n=== Pivot: Default rate by Region and Late-but-Repaid ===")
pivot = pd.pivot_table(
    df,
    index="region",
    columns="late_but_repaid",
    values="defaulted_12m",
    aggfunc="mean"
)

pivot = pivot * 100
display(pivot.round(2))


print("\n=== Late-but-Repaid = Y only ===")
late_repaid = df[df["late_but_repaid"] == "Y"]

late_summary = late_repaid.groupby("region")["defaulted_12m"].agg(
    count="count",
    defaults="sum",
    default_rate="mean"
)

late_summary["default_rate_%"] = late_summary["default_rate"] * 100
display(late_summary.round(2))


print("\n=== Difference between regions for Y ===")
if len(late_summary) > 1:
    rates = late_summary["default_rate_%"]
    print("Highest default rate:", round(rates.max(), 2), "%")
    print("Lowest default rate :", round(rates.min(), 2), "%")
    print("Difference           :", round(rates.max() - rates.min(), 2), "percentage points")

=== Overall relationship ===

                 count  default_rate  default_rate_%
late_but_repaid
N                 5016      0.204147       20.414673
Y                  334      0.446108       44.610778

=== By Region ===

            region late_but_repaid  count  default_rate  default_rate_%
0  Central Gujarat               N    988      0.213563       21.356275
1  Central Gujarat               Y     49      0.000000        0.000000
2            Kutch               N    762      0.185039       18.503937
3            Kutch               Y     58      0.879310       87.931034
4    North Gujarat               N   1013      0.217177       21.717670
5    North Gujarat               Y     56      0.000000        0.000000
6       Saurashtra               N   1523      0.204859       20.485883
7       Saurashtra               Y    114      0.859649       85.964912
8    South Gujarat               N    730      0.191781       19.178082
9    South Gujarat               Y     57      0.000000        0.000000

=== Pivot: Default rate by Region and Late-but-Repaid ===

late_but_repaid      N      Y
region
Central Gujarat  21.36   0.00
Kutch            18.50  87.93
North Gujarat    21.72   0.00
Saurashtra       20.49  85.96
South Gujarat    19.18   0.00

=== Late-but-Repaid = Y only ===

                 count  defaults  default_rate  default_rate_%
region
Central Gujarat     49         0          0.00            0.00
Kutch               58        51          0.88           87.93
North Gujarat       56         0          0.00            0.00
Saurashtra         114        98          0.86           85.96
South Gujarat       57         0          0.00            0.00

=== Difference between regions for Y ===
Highest default rate: 87.93 %
Lowest default rate : 0.0 %
Difference           : 87.93 percentage points